pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    service_name: department-service
    service_type: REST
spec:
  containers:
  - name: dnd
    image: docker:latest
    command: 
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  - name: kubectl
    image: bryandollery/terraform-packer-aws-alpine
    command:
    - cat
    tty: true
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock  
      type: Socket
"""
    }
  }
  environment {
    DOCKER_NAMESPACE = 'manarabdulrahman'
    SERVICE_NAME = 'department-service'
    //TOKEN=credentials('tester_token')
  }
  stages {
      stage("Build") {
          steps {
              container('dnd') {
                  sh '''
                      cd $SERVICE_NAME
                      docker build --tag $DOCKER_NAMESPACE/$SERVICE_NAME:v1 .
                  '''
              }
          }
      }
      stage("Release") {
          steps {
              container('dnd') {
                   withCredentials([string(credentialsId: 'docker-hub', variable: 'docker-hub-psw')]) {
                         sh '''
                                              docker login -u $DOCKER_NAMESPACE -p ${docker-hub-psw}
                                              docker push $DOCKER_NAMESPACE/$SERVICE_NAME
                                          '''
                  }

              }
          }
      }
      stage("Deploy") {
          steps {
              container('kubectl') {
                  sh '''
                      cd $SERVICE_NAME
                      kubectl --token=$TOKEN -n test apply -f deploy.yaml -f service.yaml
                  '''
              }
          }
      }
  }
}
